name: TokensWebWalletTestsCI

on: 
  push:
    branches:
    - master
    - dev

jobs:
  linux-run-tests:
    name: Unit tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true

    - name: Install deps
      run: npm install

    - name: Run tests
      run:  npm run test